server:
  port: 9999

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  server:
    error:
      include-exception: true
      include-stacktrace: always
      whiteable:
        enable: false
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: false
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: all-service-options
          uri: no://op
          predicates:
            - Method=OPTIONS
          filters:
            - NoneAuthFilter

        - id: gateway-health
          uri: no://op
          predicates:
            - Path=/health
          filters:
            - NoneAuthFilter

        - id: test-service
          uri: http://localhost:9999
          predicates:
            - Path=/v1/api/items
          filters:
            - RateLimitAuthFilter

  redis:
    host: localhost
    port: 6379